im85288/service.upnext

- addon.xml
- resources/lib/player.py
- resources/lib/utils.py
- service.py
UpNext will now listen to method "upnext_data" regardless of sender. It will send notification to addons using sender "upnextprovider" and the method "original sender's value" + "_play_action" (i.e. "embycon_play_action". That is what addons should listen to.
> Replace addon signals

- resources/lib/monitor.py
- resources/lib/player.py
This fixes the scenario where user starts playing a file, stops before last_file gets updated in up next on the next episode. Then users plays the same file, leaving last_file outdated and preventing the dialog from showing up again. 
While the up next dialog is displayed, this will prevent a user manually stopping playback from triggering up next, data will be cleared.
> Reset last_file and data upon user stopping playback

- resources/lib/playbackManager.py
- resources/lib/player.py
Having the reset in OnPlayBackStarted causes the dialog to sometimes not show up, especially if up next information is sent as OnPlayBackStarted triggers. 
It will also correct the dialog showing up when transitioning to the next episode. It discards the saved data once we are done with it.
> Fix dialog not showing up

- resources/lib/monitor.py
- resources/lib/player.py
If the play data is received before onPlayBackStated is called, the player state is then outdated with previous total time and play time, causing up next to trigger as play next starts.
> Fix play next race condition

- resources/lib/monitor.py
For when no file is playing. This should also catch if the playlist has ended.
> Disable up next tracking if no file playing

- resources/lib/player.py
Delay start tracking by 5s to ensure player information has the chance to update on slower devices and prevent up next from showing right as playback starts.
> Fix race condition on slower devices

- resources/lib/playbackManager.py
- resources/lib/player.py
- resources/lib/state.py
Move tracking to State is to better control what happens between player events and playbackManager behavior. This will allow for user stop during the up next dialog to have an effect.
> Fix stop for Kodi playback

- resources/lib/playbackManager.py
The property wasn't being cleared for short videos causing the osd to be hidden in Embuary upon starting the next item.
> Fix up next window prop clearing

- resources/lib/api.py
- resources/lib/playItem.py
- resources/lib/playbackManager.py
- resources/lib/stillwatching.py
- resources/lib/upnext.py
- resources/lib/utils.py
- resources/settings.xml
This is to resolve conflict between shuffled playlist and up next. If episodes are already queued up and we are not at the end of the playlist, grab the next episode to play from the existing playlist.
It also adds the endtime as a dialog property to reflect the endtime of the next episode when the dialog is displayed.
"runtime" could be added as an optional field to next_info data, to fill endtime value. The runtime should be in seconds.
> Add priority to existing playlist & endtime prop

- README.md
- addon.xml
The addon.xml includes indented lines in a single paragraph.
Unfortunately this causes newlines and added whitespace in the Kodi
add-on interface.
This PR fixes that.
This PR also removes trailing spaces in README.md.
> Fix prepended spaces in description

- .gitignore
- .pylintrc
- Makefile
- tox.ini
This adds sanity checks for Python, but doesn't include any fixes just
yet. Once we have everything fixed to a certain standard, we can enable
this in Travis for new contributions.
This also add a `make zip` target for creating test builds.
> This adds sanity checks for Python

- README.md
- addon.xml
- resources/settings.xml
I noticed both the summary and description where showing the same
information. Now the summary is a lot shorter, and the details are in
the description.
For the settings, I removed the default enable/visible defaults.
> Simplify summary/description and settings.xml

- resources/lib/playitem.py
In https://github.com/im85288/service.upnext/commit/e23945afa5f9e8640659af72c33f454b80bd442f existing playlist items got priority over "normal" episodes. But the logic of this implementation was just plain wrong!
This completely broke the Up Next feature when playing multiple episodes with video add-ons like Netflix. Luckily, this commit was never part of the 1.0.1 version available in the official Kodi repo, so the impact was limited.
This pull request fixes the logic taking into account the following facts:
- A playlist with only one item doesn't have a next item
- xbmc.PlayList().getposition() starts counting from zero
> Fix playlist logic

- resources/lib/utils.py
This should make the Up Next service fully functional on Kodi 19 with Python 3 while preserving support for Python 2 and all older Kodi versions.
> Fix NotifyAll data for Python 3 Kodi

- resources/lib/playbackmanager.py
@dagwieers Sometimes playcount key exists in the dictionary but has None as a value.
> fix no_play_count

- resources/lib/monitor.py
- resources/lib/utils.py
If Kodi was configured to get debug logging, ignore the add-on log level
altogether and log as DEBUG.
Since we log when the service is stopped, I opted to also log when the service is started. Otherwise it is weird if you disable and enable it, it only logged that the service was stopped, but not that it was started again.
> Act on Kodi debug logging

- resources/lib/stillwatching.py
- resources/lib/upnext.py
The user should be able to use the back button to dismiss Up Next.
This behaves as if nothing had happened, except that it is clear that
the user is still watching. It also results in Up Next not playing the
next episode.
This fixes #73
> Support Back button action

- resources/lib/statichelper.py
- resources/lib/stillwatching.py
- resources/lib/upnext.py
- Improvements to from_unicode/to_unicode (unused)
- Fix rating/playcount type to string
- Don't use from_unicode for setProperty as it accepts str and unicode
(on PY2 and PY3)
This fixes #83
> Fix non-string/unicode property values

- resources/language/resource.language.de_de/strings.po
The string "up next" has not been translated.
> Changed string "up next" to german language

- resources/lib/player.py
This fixes a bug where you get an "Up Next" notification screen to watch a **previous** episode when you play the very last episode of a series.
Steps to reproduce this bug with the Netflix add-on:
- play an episode that has a next episode
- seek beyond the end time of the episode, so you never see the "Up Next" notification and you trigger `onPlayBackEnded`
- play the very last episode of a series, so there exists no next episode
- wait until the very last episode shows the "Up Next" notification screen a previous episode
Please test if this effectively fixes this bug before merging.
> Always reset state when playback finishes

- resources/lib/utils.py
Found this on my device with OSMC installed,  looks like OSMC is using Python 3.5 (at least currently)
- fixes utils.decode_data for `Python 3.0 -> 3.5`
- json.loads didn't support bytes or bytearray until Python 3.6
> convert bytes to str before using json.loads for python < 3.6 compat

- resources/lib/playbackmanager.py
This is just a workaround because I don't think the implementation is
the best way to see if the clock is using a 24h format or not.
This fixes #106
> Fix issue with 24hour format detection

- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.hr_hr/strings.po
- resources/language/resource.language.hu_hu/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.pl_pl/strings.po
- resources/lib/utils.py
- resources/skins/default/1080i/script-upnext-stillwatching-simple.xml
- resources/skins/default/1080i/script-upnext-stillwatching.xml
- resources/skins/default/1080i/script-upnext-upnext-simple.xml
- resources/skins/default/1080i/script-upnext-upnext.xml
Since some languages do not translate like most western languages
(composed of substrings) it is better to translate sentences, rather
than substrings.
This is required for Korean and/or Japanese translations.
But it is generally a better practice anyway.
This fixes #108
> Use formatted sentences in translations

- Makefile
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.hr_hr/strings.po
- resources/language/resource.language.hu_hu/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.pl_pl/strings.po
- resources/lib/api.py
- resources/lib/developer.py
- resources/lib/monitor.py
- resources/lib/pages.py
- resources/lib/playbackmanager.py
- resources/lib/player.py
- resources/lib/playitem.py
- resources/lib/state.py
- resources/lib/stillwatching.py
- resources/lib/upnext.py
- resources/lib/utils.py
- service.py
- test/test_encoding.py
These are the non-impacting changes from PR #100.
- Selectively import classes and functions from modules
- Rename 'settings()' into 'get_setting()'
- Change 'window()' into 'clear_property()', 'get_property()' and 'set_property()'
- Use Addon instance on demand so settings are updated instantly
- No longer require a restart/reboot for settings to be applied
> Restructure some code

- .pylintrc
- resources/lib/playbackmanager.py
- resources/lib/state.py
- resources/settings.xml
This was already disabled from the settings after #100 was merged.
So I guess we can remove this functionality.
Users can now only disable the Up Next pop-up for video's smaller than
10mins by configuring a notification time of 0.
> Remove shortPlay functionality

- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.hr_hr/strings.po
- resources/language/resource.language.hu_hu/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.ja_JP/strings.po
- resources/language/resource.language.ko_KR/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.pl_pl/strings.po
- resources/skins/default/1080i/script-upnext-stillwatching-simple.xml
- resources/skins/default/1080i/script-upnext-stillwatching.xml
- A better description of Close vs Stop button
- Remove unused strings and translations
- Do not use [CAPITALIZE] for title
- Fix a few Dutch translations
> Various fixes to translations

- .pylintrc
- .travis.yml
- Makefile
- requirements.txt
- resources/lib/monitor.py
- test/test_encoding.py
- tox.ini
- Various small fixes to tests
- The use of the Addon Signals master branch for testing
This fixes tests as seen at: https://travis-ci.org/dagwieers/service.upnext/branches
> Assorted fixes

- resources/lib/playbackmanager.py
- resources/lib/stillwatching.py
- resources/lib/upnext.py
Runtime exception in playbackmanager.py if neither next_up nor still_watching pages get shown because of early abort (e.g. user skipped directly to the end of the video).
Runtime exception when displaying either page if the skin does not have the progress control (ID 3014). Was checking for None on return of getControl() but this actually raises a RuntimeError exception if the control does not exist.
> Fix various runtime exceptions

- resources/lib/api.py
Since this matches with Netflix's metadata better and changing the Netflix add-on is too hard at this time.
In the future it is likely other content providers may add this information in the same format as well.
This reimplements PR #146 since I couldn't modify the original PR.
> Add `notification_offset` for Netflix

- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.hr_hr/strings.po
- resources/language/resource.language.hu_hu/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.ja_JP/strings.po
- resources/language/resource.language.ko_KR/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.pl_pl/strings.po
- resources/lib/playbackmanager.py
- resources/lib/script.py
- resources/lib/stillwatching.py
- resources/lib/upnext.py
- resources/lib/utils.py
- resources/skins/default/1080i/script-upnext-stillwatching.xml
- resources/skins/default/1080i/script-upnext-upnext.xml
- Changes to the skin to add Time and next endtime
- New `endtime` window property
This fixes #81 
The implementation looks like this:
> Add System.Time and endtime to notification

- README.md
- addon.xml
> Prepare for v1.1.0 release

- README.md
- addon.xml
- resources/lib/utils.py
- resources/skins/default/1080i/script-upnext-stillwatching.xml
- resources/skins/default/1080i/script-upnext-upnext.xml
- Avoid showing "Ends at:" when no endtime was available
- Do not strip leading zeroes as "0:34" becomes ":34"
- Small update to changelog (French was missing)
> Do not show "Ends at:" when endtime is missing

- resources/lib/utils.py
This reimplements a bugfix (#172) from @Maven85 and documents the case.
This relates to https://github.com/xbmc/xbmc/pull/17380
This fixes #169
> Document and fix a known Kodi bug in Up Next

- resources/lib/playbackmanager.py
- resources/lib/script.py
- resources/settings.xml
Restore the option to not show the pop-up when playing from a playlist.
This prevents a couple issues:
1. Breaking the playlist if the current show has further episodes.
2. Episodes continue playing regardless of the user choice to not continue watching on the pop-ups.
> Restore "Ignore Playlist" option

- resources/lib/monitor.py
- resources/lib/playbackmanager.py
Kodi can't track playback position for external players, so not only we can't tell when to show the pop-up, but when it is displayed (I'm guessing based on `playcountminimumtime` tag from `playercorefactory.xml` - [ref](https://kodi.wiki/view/External_players)) the external player might lose focus and stop playback (was my experience at least, ymmv).
> Avoid conflict with external players

- resources/lib/api.py
- resources/lib/playbackmanager.py
- resources/lib/player.py
- resources/lib/state.py
- tests/xbmc.py
Will enqueue the next episode to the playlist in launch_popup() and, by default, will play local media and addon media (where play_url is provided) as per normal playlist handling method. Will use existing local and addon media playback methods if the next episode is not added to the playlist (not actually checking if playlist item was successfully added, files match, playlist size increased by one, etc. as it didn't seem necessary)
Note that call to self.player.seekTime() in launch_popup() never seemed to work properly (caused the player to seek and continue playing past the file end time) and I'm not sure why this method was used rather than simply skipping to the next playlist item using self.player.playnext(). In any case both methods are now utilised, without any apparent problems on …
> Enqueue the next episode in the playlist

- resources/lib/monitor.py
- resources/lib/utils.py
This avoids testing for Player.isExternalPlayer() on Kodi v17 which does not
support this.
This fixes #214
> Add Kodi v17 compatibility

- resources/lib/playbackmanager.py
- resources/settings.xml
- Enable `customAutoPlayTime` by default
- No longer skip to end
First of all, skipping the credits is not needed in the majority of cases, because the pop-up appears within the 90% default margin in Kodi.
Secondly, this seeking, when done using VOD add-ons, causes the player to exit before the next items is being played, so it doesn't give a nice user experience.
I no longer think this is a real problem, only for videos shorter than 5 mins (or 2.5 mins for customAutoPlay) this becomes an issue.
For Netflix it would mean that:
- For a 10 min episode would have issues if the credits shows earlier than 60 seconds.
- For a 30 min episode the credits should not appear before the last 180 seconds.
- For a 1 hour episode the credits should not appear before the last 360 …
> Enable customAutoPlay by default and get rid of seekTime()

- resources/language/resource.language.cs_cz/strings.po
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.es_es/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.hr_hr/strings.po
- resources/language/resource.language.hu_hu/strings.po
- resources/language/resource.language.in_hi/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.ja_jp/strings.po
- resources/language/resource.language.ko_kr/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.pl_pl/strings.po
- resources/language/resource.language.pt_br/strings.po
- resources/language/resource.language.ro_ro/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sk_sk/strings.po
- resources/language/resource.language.sv_se/strings.po
- resources/lib/demo.py
- resources/lib/monitor.py
- resources/lib/playbackmanager.py
- resources/lib/player.py
- resources/lib/playitem.py
- resources/lib/stillwatching.py
- resources/lib/upnext.py
- resources/settings.xml
- tests/xbmcgui.py
The Developer section in the settings now has a DEMO mode switch.
If this is enabled, every playback will skip to the near-end to test the
behaviour of the UpNext add-on in high speed.
This allows testing e.g. StillWatching functionality.
> Implement DEMO mode

- README.md
- addon.xml
> Prepare for v1.1.3 release

- .github/workflows/addon-check.yml
- .github/workflows/ci.yml
With the release of Python 3.9 we better test our code on the latest Python.
> Add support for Python 3.9

- resources/lib/api.py
- resources/lib/playbackmanager.py
- resources/lib/player.py
- resources/lib/state.py
This is an interim fix to the unwanted playback problem, originally identified by @thebertster in #204 and also subsequently by others in #227.
Note that this wont fix all the issues that were identified in the discussion associated with #204, but should address the most common problem for most installations.
> Fix to prevent unwanted playback when using playlist queueing method

- resources/lib/monitor.py
- resources/lib/player.py
Addresses https://github.com/xbmc/xbmc/issues/19378
Video mediatype may be discarded when a listItem VideoInfoTag is merged.
This can prevent UpNext from working with an addon, even if the addon sends the data required for UpNext to function, as UpNext checks the videoplayer.content(episodes) infobool for all video content, when this is only actually needed for library content.
Note that this should also be fixed for playlist content, however that change is a little bit more complicated and requires more significant modifications.
@Dis90 would you mind testing if this resolves the original problem you were having?
> Fix for missing mediatype video info with addon video content

- resources/language/resource.language.ru_ru/strings.po
I fixed the "Up Next" header in the popup not being translated. I think there should be some clarification added that this is not the extension's title and that it should, in fact, be translated.
> Update Russian translation

- resources/lib/api.py
Fix for secondary issue identified in #271 - filenames stored in library may not match filename actually being played e.g. when using strm files or other playlist like files.
> Update check for filename of multi-part episodes

- resources/lib/playbackmanager.py
Addresses https://github.com/im85288/service.upnext/issues/199#issuecomment-786277367 and #283
- Currently the comparison of played episodes is effectively made to played_in_a_row_number + 1, which means that a user would set the Number of episodes before "Still there?" query setting to 3, for example, but the Still Watching? popup would only show up if 4 episodes have played and the 5th episode was about to play. Now it will show up if 3 episodes have played.
- Currently there is no way to disable the Still Watching? popup. Now, changing the Number of episodes before "Still there?" query to 0 should disable it, and setting to 1 should make it appear all the time.
> Make the played in a row setting a little clearer

- resources/lib/monitor.py
Possible fix for #286. Completely untested.
Not sure why from_unicode was being used originally?
> Fix handling of non-ASCII filenames for Kodi18

- .github/workflows/ci.yml
@im85288 - I noticed that a number of the existing workflows were failing. Have fixed most of them up, but the SonarCloud integration looks like it will need a new user authorisation token to be created.
You will need to go to https://sonarcloud.io/account/security to (re)create the user token.
Then go to https://github.com/im85288/service.upnext/settings/secrets/actions and create a new repository secret named `SONAR_TOKEN` with the secret set to the newly created user token.
> Fix SonarCloud integration

- resources/lib/playbackmanager.py
Timing issues stemming from #305 can result in incorrect or double playback attempts
> Fix potential loss of queue state due to pre-emptive queue reset
