resources/language/resource.language.pl_pl/strings.po
=> Add polish translation

resources/lib/player.py
removed tabs, because it broke the addon so kodi won't start it.
=> removed tabs in resources/lib/player.py

resources/language/resource.language.en_gb/strings.po, resources/lib/playbackManager.py, resources/lib/player.py, resources/lib/state.py, resources/settings.xml, resources/skins/default/1080i/script-upnext-stillwatching-simple.xml, resources/skins/default/1080i/script-upnext-stillwatching.xml, resources/skins/default/1080i/script-upnext-upnext-simple.xml, resources/skins/default/1080i/script-upnext-upnext.xml
Modify dialogs to hide countdown for time remaining above 60 seconds. 
Add a pause/resume for the progress reported in dialogs.
=> Extend notification time to 180

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.pl_pl/strings.po, resources/lib/upnext.py, resources/settings.xml
Connected to this: https://github.com/im85288/service.upnext/pull/15#issuecomment-489321254
I made it as an option in the menu (off by default), I checked on several movies on Netflix and several of the kodi library - it works.
=> Automatic stop playing (as option)

.gitignore, .travis.yml, resources/__init__.py, resources/lib/__init__.py, resources/lib/api.py, resources/lib/developer.py, resources/lib/monitor.py, resources/lib/pages.py, resources/lib/playItem.py, resources/lib/playbackManager.py, resources/lib/player.py, resources/lib/state.py, resources/lib/stillwatching.py, resources/lib/upnext.py, resources/lib/utils.py, service.py
This implements fixes for all reported flake8 issues.
Beware of two things that require more testing:
- defaulting to unicode for string literals
- unicode_to_ascii implementation
=> Fix all existing flake8 issues

resources/lib/api.py, resources/lib/developer.py, resources/lib/monitor.py, resources/lib/pages.py, resources/lib/playbackmanager.py, resources/lib/player.py, resources/lib/playitem.py, resources/lib/state.py, resources/lib/stillwatching.py, resources/lib/upnext.py, resources/lib/utils.py
This implements fixes for all reported flake8 issues.
Beware of two things that require more testing:
- pylint complains about that Control does not have setPercent ?
=> Fix all pylint issues

addon.xml
I was looking for this dependency and I couldn't find it.
=> Remove requests dependency

.github/codecov.yml, .gitignore, .pylintrc, .travis.yml, Makefile, requirements.txt, resources/lib/api.py, resources/lib/developer.py, resources/lib/monitor.py, resources/lib/pages.py, resources/lib/playbackmanager.py, resources/lib/player.py, resources/lib/playitem.py, resources/lib/state.py, resources/lib/statichelper.py, resources/lib/stillwatching.py, resources/lib/upnext.py, resources/lib/utils.py, test/test_unicode.py, test/userdata/addon_settings.json, test/userdata/global_settings.json, test/xbmc.py, test/xbmcaddon.py, test/xbmcextra.py, test/xbmcgui.py, test/xbmcplugin.py, test/xbmcvfs.py
This PR adds:
- More flake8 and pylint fixes (got lost during conflict resolution)
- Include Kodi stubs
- Integration tests for testing all codepaths *-- Unfinished*
- Unit tests (for unicode and python2/3) *-- TODO*
- Code coverage testing
=> Add unit tests

resources/lib/api.py, resources/lib/monitor.py, resources/lib/pages.py, resources/lib/playbackmanager.py, resources/lib/playitem.py, resources/lib/stillwatching.py, resources/lib/upnext.py, resources/lib/utils.py
- A fix for an exception when logging when the add-on is disabled
- Replace all dict access using the more forgiving get()
- Some more unicode fixes
=> Fix exception when exiting add-on

.travis.yml, Makefile, resources/language/resource.language.nl_nl/strings.po, resources/lib/api.py, resources/lib/monitor.py, resources/lib/playbackmanager.py, resources/lib/playitem.py, resources/lib/utils.py
- Fix for stopping service.py gracefully
- Simplify utils.log() interface
- Dutch translation fix
- Redesign JSONRPC (ought to become a function, imo)
- Add documentation to utils.py
- Two unicode improvements
=> WIP: Assorted set of fixes

resources/language/resource.language.de_de/strings.po, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.hu_hu/strings.po, resources/language/resource.language.it_it/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/language/resource.language.pl_pl/strings.po, resources/lib/upnext.py, resources/lib/utils.py, resources/skins/default/1080i/script-upnext-upnext.xml, test/xbmcgui.py
- If configured, relabel the Close button as Stop
- Use spaces not tabs for nextup XML, no other changes, just consistency
=>  Close button label

resources/lib/api.py
This fixes the following issues:
```
File "/storage/.kodi/addons/service.upnext/resources/lib/api.py", line 201, in find_next_episode
while result.get('result').get('episodes')[position].get('file') == current_file:
IndexError: list index out of range
```
And cleans up some of the logic.
=> Fix IndexError: list index out of range

Makefile, resources/language/resource.language.de_de/strings.po, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.hu_hu/strings.po, resources/language/resource.language.it_it/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/language/resource.language.pl_pl/strings.po
- A fix for the translation tests in Makefile
- A fix for the German .po file as reported by msgcmp
- Make all translations consistent
=> Translation fixes

addon.xml
=> Add SPDX identifier for license

Makefile, addon.xml, default.py
This adds an entry in the add-on section for Up Next.
=> Add a program entry in the addon section

.travis.yml, Makefile
This includes:
- Hardcode addon.xml
- Do not hardcode language list
- Make python binary variable
- Add codecov syntax check
- Do not fail on language check
=> Various small changes to Makefile

Makefile, resources/language/resource.language.de_de/strings.po, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.hr_hr/strings.po, resources/language/resource.language.hu_hu/strings.po, resources/language/resource.language.it_it/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/language/resource.language.pl_pl/strings.po, resources/lib/api.py, resources/lib/developer.py, resources/lib/monitor.py, resources/lib/pages.py, resources/lib/playbackmanager.py, resources/lib/player.py, resources/lib/playitem.py, resources/lib/state.py, resources/lib/stillwatching.py, resources/lib/upnext.py, resources/lib/utils.py, resources/settings.xml, service.py, test/test_encoding.py
This implements reorganized settings:
- 3 sections: Interface, Behaviour, Expert
- Customize the notification time by episode length
- Various improvements to translation strings
The changes are in the second commit (adf6dd08bee69937c34948cdc5d2b95604d60c7f), the first commit is PR #114.
The new settings look like this:
=> Implement new settings

resources/language/resource.language.pl_pl/strings.po
Update Polish strings to the latest changes
=> Update Polish strings

resources/language/resource.language.ja_JP/strings.po, resources/language/resource.language.ko_KR/strings.po
Added Japanese and Korean translation
=> Translation JP/KR

.codecov.yml, .travis.yml, Makefile, resources/lib/playbackmanager.py, resources/lib/script.py, resources/lib/statichelper.py, resources/lib/stillwatching.py, resources/lib/upnext.py, test/xbmc.py
This ensures that we are not suppressing things that aren't being
reaised to begin with (i.e. because we fixed the underlying cause).
=> Report pylint useless suppressions

resources/lib/api.py, resources/lib/playbackmanager.py, resources/lib/utils.py
This adds support for playing the next episode directly from UpNext.
This fixes #132
=> Implement play_url support

resources/language/resource.language.de_de/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.hr_hr/strings.po, resources/language/resource.language.hu_hu/strings.po, resources/language/resource.language.it_it/strings.po, resources/language/resource.language.ja_JP/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/language/resource.language.pl_pl/strings.po
This fixes known issues with translation files without actually
translating anything.
This relates to #112
=> Assorted translation fixes

resources/language/resource.language.hr_hr/strings.po
update to Croatian hr_hr translation
=> update Croatian hr_hr #112

resources/language/resource.language.sk_sk/strings.po
Good luck, hopefully, I have understand to functions well.
=> Add slovak translation

resources/language/resource.language.fr_fr/strings.po
For issue #112.
Translated missing strings and updated some.
=> Update french translation

resources/language/resource.language.es_es/strings.po, resources/language/resource.language.hr_hr/strings.po, resources/language/resource.language.ja_jp/strings.po, resources/language/resource.language.pt_br/strings.po
- Translation of 'Ends at' in Spanish
- Comments cause issue in Hungarian
- Syntax error in Japanese (still another error)
- Syntax error in Brazilian
=> Small fixes to existing language files

resources/lib/api.py, resources/lib/monitor.py, resources/lib/player.py, resources/lib/script.py, resources/lib/script_entry.py, resources/lib/statichelper.py, resources/lib/utils.py
This fixes docstrings as done in other projects. (PEP 257)
https://www.python.org/dev/peps/pep-0257/
=> Fix docstrings

resources/language/resource.language.ro_ro/strings.po
Added initial Romanian translation based on the English strings
=> Add initial Romanian translation

resources/lib/monitor.py, tests/xbmcgui.py
This helps with troubleshooting #176
=> Log data on JSON decode errors

.github/workflows/addon-check.yml, requirements.txt, tests/xbmc.py
- Remove libxml2 dependency causing issues
- Remove travis reference
- Add Player.isExternalPlayer() stub method (for #184)
=> Small fixes

resources/lib/api.py, resources/lib/monitor.py, resources/lib/playbackmanager.py, resources/lib/script.py, resources/lib/state.py, resources/lib/upnext.py, resources/lib/utils.py, resources/settings.xml, tests/userdata/addon_settings.json
This adds a type-option to set_setting so we can force the type when reading a value.
And by doing so I fixed a few potential issues as well...
=> Add support for Addon setting types

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile, tests/xbmcextra.py
This adds a release workflow to GitHub CI so that pushing a new release
tag will automatically create a GitHub release and pushes out a Leia and
Matrix release to Kodi.
=> Add release workflow

README.md, addon.xml
=> Prepare for v1.1.1 release

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, addon.xml
A few more cleanups and fixed dates.
=> Prepare for v1.1.1 release (the sequel)

resources/lib/script.py
This was requested by Kodi devs.
=> Add check for abortRequested

README.md
Since this information is on GitHub we might as well add it to the
README too.
=> Update the README changelog with earlier releases

.github/workflows/addon-check.yml, .github/workflows/ci.yml, .pylintrc
- Using upstream sonarcloud action with new functionality
- Revert back to using kodi-addon-checker pip package
=> Clean up workflows

resources/lib/utils.py
(cherry picked from commit e175596375d65886a1088f78007db91ec226346e)
=> Update logging function to address #205

resources/lib/script.py, tests/xbmcgui.py
Fixes pylint complaints, use monitor rather than sleep
Note that method for creating test popup will be replaced in later PR
=> Minor fixes

resources/lib/playbackmanager.py
So this served a purpose, now document it better.
=> Restore the conditional playnext()

resources/language/resource.language.ro_ro/strings.po
Translated new strings to Romanian for version 1.1.3
=> Update Romanian translation [ro_ro] for v1.1.3

resources/lib/player.py
This has big implications and was simply a test, not intended to be
released.
This fixes #226
=> Revert test change

README.md, addon.xml
=> Prepare for v1.1.4 release

resources/lib/api.py, resources/lib/playbackmanager.py, resources/lib/playitem.py, resources/lib/utils.py
Attempt to fix various playlist handling issues as per https://github.com/im85288/service.upnext/issues/134#issuecomment-776325417
Some quick testing indicates that this appears to work as described above, but as the changes were taken from a branch that has diverged significantly from master, probably best if it was tested a little bit more thoroughly.
=> Fix playlists to work with non-library content

Makefile
An attempt to fix multizip on Bash and Busybox.
This relates to a problem reported in #227
=> Fix escaped chars for multizip

README.md, addon.xml
=> Prepare for v1.1.5 release

resources/lib/player.py
To fix #238 (and a bunch of other problems)
=> Use onAVStarted instead of onPlayBackStarted

resources/lib/api.py, resources/lib/playitem.py, tests/xbmc.py, tests/xbmcvfs.py
Fixes #255
Also fixes pylint complaints that were causing tests to fail
=> Fix for Kodi not using the video player/playlist to play videos

resources/language/resource.language.zh_tw/strings.po
=> update with new language "zh_tw"

resources/skins/default/1080i/script-upnext-upnext.xml
=> Fixes misalignment of system.time and endtime

.github/workflows/ci.yml, .pylintrc, requirements.txt, resources/lib/api.py, tests/xbmcaddon.py, tests/xbmcextra.py, tests/xbmcvfs.py
=> Patch workflows and pylint

resources/lib/monitor.py
=> Check for physical disc or disc image being played

README.md, addon.xml
Update addon.xml and README.md
=> Release 1.1.8

.github/workflows/ci.yml, requirements.txt, resources/lib/api.py, resources/lib/playbackmanager.py, resources/lib/utils.py, tests/test_service.py, tests/xbmc.py, tests/xbmcextra.py, tox.ini
Update dependencies/requirements, installation and steps in ci workflow
Also fix/ignore old pylint complaints that were causing the workflow to fail and update stubs
=> Fix failing ci workflow

resources/language/resource.language.sv_se/strings.po
Some minor tweaks and corrections
=> Update Swedish translation

addon.xml
Fix error in addon description. Sorry.
=> Update addon.xml for spanish translation

resources/lib/player.py
=> Workaround for Trakt playlist monitoring

resources/lib/stillwatching.py, resources/lib/upnext.py, resources/lib/utils.py
=> Use localised date in popups
